### ISSUE TITLE
Working with Googlmapper

### ISSUE THREAD

**Issue by Afterspace** [midnite81/geolocation#3]
Hello, i have recently started out fiddling about with Laravel, and im trying to get geolocation data from your api and use it in Googlmapper as a source of longitude and latitude, 

```
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Cornford\Googlmapper\MapperServiceProvider;
use Geocoder\Laravel\Facades\Geocoder;
use Midnite81\GeoLocation\Contracts\Services\GeoLocation;
use Illuminate\Http\Request;

use Mapper;


class MapController extends Controller
{
    /**
     * Show the profile for the given user.
     *
     *
     * @return Response
     */
    public function index(GeoLocation $geo, Request $request)
    {
        $location = $geo->getCity($request->ip());

        $lat = $location->getLatitude();
        $lon = $location->getLongitude();
        
        Mapper::map(53.381128999999990000, -1.470085000000040000, ['zoom' => 15, 'markers' => ['title' => 'My Location', 'animation' => 'DROP']]);
      
        return view('welcome');
    }
}
```

When i replace into the Mapper:map($lat,$lon, .... ) i am not getting a map at all, just blank space on the view. 
Additional info, i have followed all the steps from your github and everything is in order, i am testing this on localhost where location services are enabled for me. 

Just making this post in hope that you can guide me,or help me understand how to use your GeoLocation services. Thanks in advance

**Comment by midnite81** [comment]
Hi there, 

When you say location services are enabled for you on localhost, I am wondering if you mean that your browser supports client side geolocation. 

This package uses the IP address to get location information. Localhost would not return anything because a localhost can be anyone's pc. 

What I would try initially is `dying and dumping` out the response e.g. 

```
    /**
     * Show the profile for the given user.
     *
     *
     * @return Response
     */
    public function index(GeoLocation $geo, Request $request)
    {
        $location = $geo->getCity($request->ip());

        dd($location); 
```

This will return something I expect like the following; 

```
Midnite81\GeoLocation\Services\IpLocation {#1026
     +statusCode: "OK",
     +statusMessage: "",
     +ipAddress: "127.0.0.1",
     +countryCode: "-",
     +countryName: "-",
     +regionName: "-",
     +cityName: "-",
     +zipCode: "-",
     +latitude: "",
     +longitude: "",
     +timeZone: "-",
     +addressString: "-, -, -",
   }

```

Try replacing, temporarily, the $request->ip() to `$location = $geo->getCity('8.8.8.8);`

This is google's DNS ip - so should return something similar to the following response. 

```
Midnite81\GeoLocation\Services\IpLocation {#1008
     +statusCode: "OK",
     +statusMessage: "",
     +ipAddress: "8.8.8.8",
     +countryCode: "US",
     +countryName: "United States",
     +regionName: "California",
     +cityName: "Mountain View",
     +zipCode: "94043",
     +latitude: "37.406",
     +longitude: "-122.079",
     +timeZone: "-08:00",
     +addressString: "Mountain View, California, United States",
   }
```

If this works, it is likely that you will need it to be on a remote server so it can pick up your external IP. You probably should check that `$lon` and `$lat` are not empty/null before you create your Mapper.

Something like; 

```
if (! empty($lon)) && ! empty($lat)) { 
    Mapper::map(53.381128999999990000, -1.470085000000040000, ['zoom' => 15, 'markers' => ['title' => 'My Location', 'animation' => 'DROP']]);
}
```

I hope this helps. Let me know how you get on.

**Comment by Afterspace** [comment]
I realized that a bit later after fiddling around, i echo-ed the getip method only and it printed out only 127.0.0.1 , so i figured i'd have to be on an actual server in order to get the proper ip :) many thanks for this, and yeah, really great job and documentation on this, it was so easy to setup and use as a beginner myself!

**Comment by midnite81** [comment]
I'm glad I could be of help. When you're starting out it can be a bit daunting but you'd doing the right thing by trying!
